//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.Employees1 = new HashSet<Employees>();
            this.Employees11 = new HashSet<Employees>();
            this.Events = new HashSet<Events>();
            this.Trainings = new HashSet<Trainings>();
            this.VacationCalendar = new HashSet<VacationCalendar>();
        }
    
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronym { get; set; }
        public System.DateTime Birthdate { get; set; }
        public string WorkPhone { get; set; }
        public string Room { get; set; }
        public string WorkEmail { get; set; }
        public Nullable<int> OrganisationId { get; set; }
        public Nullable<int> DepartmentLevel1Id { get; set; }
        public Nullable<int> DepartmentLevel2Id { get; set; }
        public Nullable<int> DepartmentLevel3Id { get; set; }
        public int RoleId { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<int> AssistantId { get; set; }
        public string Info { get; set; }
    
        public virtual DepartmentLevel1 DepartmentLevel1 { get; set; }
        public virtual DepartmentLevel2 DepartmentLevel2 { get; set; }
        public virtual DepartmentLevel3 DepartmentLevel3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employees> Employees1 { get; set; }
        public virtual Employees Employees2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employees> Employees11 { get; set; }
        public virtual Employees Employees3 { get; set; }
        public virtual Organisation Organisation { get; set; }
        public virtual Roles Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Events> Events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trainings> Trainings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VacationCalendar> VacationCalendar { get; set; }
    }
}
