//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WSDBEntities : DbContext
    {
        private static WSDBEntities _context {get; set;}
        public WSDBEntities()
            : base("name=WSDBEntities")
        {
        }
        public static WSDBEntities GetContext()
        {
            if (_context == null)
            {
                _context = new WSDBEntities();
            }
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DepartmentLevel1> DepartmentLevel1 { get; set; }
        public virtual DbSet<DepartmentLevel2> DepartmentLevel2 { get; set; }
        public virtual DbSet<DepartmentLevel3> DepartmentLevel3 { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Organisation> Organisation { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<TrainingMaterials> TrainingMaterials { get; set; }
        public virtual DbSet<Trainings> Trainings { get; set; }
        public virtual DbSet<VacationCalendar> VacationCalendar { get; set; }
        public virtual DbSet<VacationTypes> VacationTypes { get; set; }
        public virtual DbSet<WorkingCalendar> WorkingCalendar { get; set; }
    }
}
