//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingMaterials
    {
        public int Id { get; set; }
        public int TrainingId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public string Area { get; set; }
        public string Author { get; set; }
    
        public virtual Trainings Trainings { get; set; }
    }
}
