//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacationCalendar
    {
        public int Id { get; set; }
        public int TypeId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual VacationTypes VacationTypes { get; set; }
    }
}
